services:
  postgres:
    image: postgres:17.4-alpine3.21
    container_name: fastapi-users-redis_db
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data_mr:/var/lib/postgresql/data
    env_file:
      - ".env"

volumes:
  postgres_data_mr: